name: Run Scraper

on:
  schedule:
    - cron: "0 6 * * *"   # daily at 6 AM UTC
  workflow_dispatch:       # allow manual runs

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install playwright
          playwright install --with-deps firefox

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push new CSV file
        uses: stefanzweibrot/git-auto-commit-action@v5
        with:
          commit_message: "Automated: Update FFXIV rankings"
          add_options: "--all"
          file_pattern: "scraped_data/*.csv" # Commits any CSV file in the scraped_data directory
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"

      - name: Upload Playwright trace
        uses: actions/upload-artifact@v4
        with:
          name: playwright-trace
          path: trace.zip
