name: Run Daily Scraper

on:
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 2:00 AM UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install System-Level Build Tools
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Use a compatible version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt


    - name: Install Playwright Browsers
      run: playwright install chromium

    - name: Run scraper
      run: python scraper.py

    - name: Commit and push results
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add scraped_data/*.csv
        git commit -m "Update rankings CSV [skip ci]" || echo "No changes to commit"
        git push
